### ISSUE TITLE
How to pass these step ENV into gradleExecuteBuild?

### ISSUE THREAD

**Issue by JosephCen** [SAP/project-piper-action#162]
For step 'gradleExecuteBuild', how to pass below ENV to the gradle execution docker container? 

``` yaml
Run SAP/project-piper-action@main
  with:
    step-name: gradleExecuteBuild
    flags: --publish --createBOM
  env:
    PIPER_ACTION_PIPER_VERSION: latest
    PIPER_ACTION_SAP_PIPER_VERSION: latest
    PIPER_ACTION_SAP_PIPER_OWNER: project-piper
    PIPER_ACTION_SAP_PIPER_REPOSITORY: sap-piper
    PIPER_ACTION_GITHUB_ENTERPRISE_TOKEN: ***
    PIPER_ACTION_PIPELINE_ENV: {****}
```

I want to access these ENV in build.gradle with below code:

``` groovy
System.getenv('PIPER_ACTION_PIPELINE_ENV')
```
