### ISSUE TITLE
allow to use a fixed version of the binay

### ISSUE THREAD

**Issue by fwilhe** [SAP/project-piper-action#2]
Currently we're always downloading the "latest" binary. It should be possible to download a fixed version to ensure reproducible builds. This might work similar to the "setup go" or "setup node" actions.

```yml
steps:
- uses: SAP/project-piper-action@v1.0
  with:
    version: 1.13.x
```

**Comment by CCFenner** [comment]
The current approach loads the binary from `https://github.com/SAP/jenkins-library/releases/latest/download/piper`, which is the **latest released binary** (created every Monday). 
We should also allow to download the latest `piper_master` binary.

**Comment by marcusholl** [comment]
To my understanding it is possible to consume an un-released version of the action. In that case the `master` branch is used. Beside that we have to support use of released versions of the action (tag).

In case I understood this right: what about

* using an unreleased version of the piper go binary in case we use the unreleased version of the action (... action on master, piper go binary from master) and 
* using the latest released version from the piper go binary (... certain tag (stable)) in case we used a released version of the action?

IMO there is nothing wrong with deliberately providing any other piper binary version, even a symbolic ref like "latest" for a released version of the action, but in order to avoid confusion we should - by default - use a fixed released version of the piper binary for released versions of the action.

Using a floating version of the piper go lib for a released version of the action can IMO be compared with having a released maven artefact having snapshot versions as dependencies.

**Comment by fwilhe** [comment]
So we all agree that we should have the option to use: 

* latest release
* master
* specific version

Disagreement is if the default for a release of the action should use a fixed version. I think there are good arguments for both, and mostly it depends on how much you value reproducibility of builds versus getting latest and greatest automatically. Similar to if you fix a version of the jenkins lib or consume `master`.

Not sure how to resolve this as I don't see agreement.

**Comment by fwilhe** [comment]
Another (very advanced and developer centric) extension of this might be to build a binary from a specific commit or branch or forked repo which might be useful for features still in development. 

Idea for syntax: 

Using a prebuilt binary:

```yaml
- uses: SAP/project-piper-action@v1.0
  with:
    version: 1.13.x
```

No version: Use "default" (latest release)
```yaml
- uses: SAP/project-piper-action@v1.0
```

Use a specific commit from SAP/jenkins-library

```yaml
- uses: SAP/project-piper-action@v1.0
  with:
    devVersion:
      commitish: fbc6ec0c64cc4a9f0ca5ef76b5ed76b6a9324edc
```

Use a feature branch from a fork
```yaml
- uses: SAP/project-piper-action@v1.0
  with:
    devVersion:
      repo: fwilhe/mything
      commitish: my-cool-thing
```

You can't use both `version` and `devVersion` together.
