### ISSUE TITLE
mtaBuild failed - ERROR could not create the "Makefile_20250202212143.mta"" file: open Makefile_20250202212143.mta: permission denied

### ISSUE THREAD

**Issue by miyasuta** [SAP/project-piper-action#243]
I have configured my workflow as follows (no configuration file other than this has been provided) :
```
name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      uses: SAP/project-piper-action@main
      with:
        step-name: mtaBuild
```
The workflow failed with the following error:
```
error mtaBuild - [2025-02-02 21:21:43] ERROR could not create the "Makefile_20250202212143.mta"" file: open Makefile_20250202212143.mta: permission denied
```
It seems that the error is caused by missing privileges, but I haven't found a way to resolve it.
The code is available here:  https://github.com/miyasuta/github-action-piper
Any input would be appreciated!
