### ISSUE TITLE
how to use credentials for deployment

### ISSUE THREAD

**Issue by navinkrishnan** [SAP/project-piper-action#82]
Hi Colleagues,

I'm doing some poc to use the piper libraries in github actions.

I would like to deploy my application to `Cloud Foundry`. 
I understand that, we need to use library step as below

```
cloudFoundryDeploy(
    script: script,
    deployType: 'blue-green',
    cloudFoundry: [apiEndpoint: 'https://test.server.com', appName:'cfAppName', credentialsId: 'cfCredentialsId', manifest: 'cfManifest', org: 'cfOrg', space: 'cfSpace'],
    deployTool: 'cf_native'
)
```
**How to pass the `credentialsId` ?**
In Jenkins this comes from the credentials plugin. In Github actions how to define this credentials Id ?

In the Github secrets, I have defined a json
```
{
username: xxx
password: xxx
}
```
and give the secret id in the plugin. But this doesn't seem to work.

Can you guide me, how to use this library step to deploy ?

Regards,
Navin

**Comment by fwilhe** [comment]
Hi @navinkrishnan 

not sure if you can use a json value here. What I did was to create secrets for each value as in this example

![Screenshot 2021-04-20 at 17 43 05](https://user-images.githubusercontent.com/2292245/115425650-1884fb00-a200-11eb-8ce9-03077637e35c.png)

And then to pass them via environment variables as in this example

```yaml
      - name: cloudFoundryDeploy
        uses: SAP/project-piper-action@master
        with:
          command: cloudFoundryDeploy
        env:
          PIPER_username: ${{ secrets.CF_USER }}
          PIPER_password: ${{ secrets.CF_PASSWORD }}
```

You can find an [example here](https://github.com/SAP/jenkins-library-test/blob/cf-deploy/.github/workflows/sap-cloud-sdk-archetype-projects.yml#L76).

The schema of the environment variable mapping (if I remember correctly, done this last half a year ago) is that `PIPER_something` will be the same as if you pass `--something` on the cli, or if you have `something` as a key in your `.pipeline/config.yaml` file.

Hope this helps,

Florian
